### PR TITLE
Add 7.2.10-rc2 release link

### PR DESCRIPTION
**Pull request by adamus1red**

### CODE REVIEW

**Comment by Zarthus** [comment]
if it's under the section "stable release", it probably shouldn't include release candidates. (i'm also not sure why the shift to .xz)

**Comment by adamus1red** [comment]
Shift to .xz because that's what the latest release is delivered as here [https://github.com/atheme/atheme/releases/tag/v7.2.10-r2](https://github.com/atheme/atheme/releases/tag/v7.2.10-r2)

**Comment by Zarthus** [comment]
That doesn't look like a RC though, but a full on release.

**Review by Zarthus — APPROVED** [review]
looks like this page has some mixed whitespace (tabs/spaces), but it looks inconsistent overall.

**Pull request merged**
